name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

    # Step 3: Move the file to output folder
      - name: Move Snake to Output Directory
        run: |
            mkdir -p output
            mv dist/snake.svg output/github-contribution-grid-snake.svg
  
        # Step 4: Commit and push the snake.svg file to the repository
      - name: Commit and Push snake.svg
        run: |
            git config --local user.name "GitHub Actions"
            git config --local user.email "actions@github.com"
            git add output/github-contribution-grid-snake.svg
            git commit -m "Add snake animation"
            git push origin master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

